common: &common
  weibo:
    api_key: "144813434"
    api_secret: "5f7880a16c798e307a218f8532d8431f"
    redirect_uri: "http://112.124.17.179/"
production:
  <<: *common

development:
  <<: *common

test:
  <<: *common