production:
 solr:
  hostname: localhost
  port: 8080
  log_level: WARNING
  
development:
 solr:
  hostname: 192.168.56.102
  port: 8080
  log_level: INFO

test:
 solr:
  hostname: localhost
  port: 8981
  log_level: WARNING
